<?php
// Export of Advanced Custom Fields (acf) for bi-weekly updates
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_bi-weekly-updates',
		'title' => 'bi-weekly-updates',
		'fields' => array (
			array (
				'key' => 'field_5706c132b4aec',
				'label' => 'What have you been working on over the past two weeks?',
				'name' => 'past_week',
				'type' => 'wysiwyg',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5706c1d094be4',
				'label' => 'For the next two weeks I will be concentrating on...',
				'name' => 'next_two_weeks',
				'type' => 'wysiwyg',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5706c18bc530f',
				'label' => 'Do you have anything that needs to be posted or broadcast?',
				'name' => 'broadcast',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5706c1fc94be5',
				'label' => 'What I need from staff in the way of support',
				'name' => 'support',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5706c0d8b4aeb',
				'label' => 'Did you attend any meetings or conferences last week?',
				'name' => 'meetings',
				'type' => 'wysiwyg',
				'instructions' => 'What meetings did you attend that are of interest to the organization?',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_571663ca58f17',
				'label' => 'Who/what was the target audience?',
				'name' => 'audience',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5716640158f18',
				'label' => 'What were the most relevant points to remember?',
				'name' => 'relevant_points',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5716795258f19',
				'label' => 'Is there any required follow-up activity?',
				'name' => 'follow-up',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5716797658f1a',
				'label' => 'Did you meet anyone that CLIR should stay in touch with via e-bulletins, etc? Anyone who might be interested in sponsoring CLIR/DLF?',
				'name' => 'contacts',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5716799a58f1b',
				'label' => 'Would you attend again?',
				'name' => 'attend_again',
				'type' => 'radio',
				'choices' => array (
					'NA' => 'NA',
					'Yes' => 'Yes',
					'No' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'NA',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'staff_updates',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'custom_fields',
				2 => 'comments',
			),
		),
		'menu_order' => 0,
	));
}
